// قائمتان مشهورتان في العالم — بياناتٌ خالصة بلا شبكة (D-388).
//
// طلبُ أحمد: «ابحث عن الليستات المشهورة في النت وضيفها».
//
// **لماذا الاسمُ والسنةُ لا المعرّف**: نفسُ حجّة `awards.ts` حرفاً —
// معرّفاتُ TMDB لا تُكتب باليد لمئة عملٍ بلا خطأ، **والاسمُ + السنةُ
// يثبّتهما `searchByName`، ومن لا يُطابَق يسقط بصمتٍ بدل أن يكسر
// القائمة**. **وقائمةُ ٩٦ فيلماً أصدقُ من لا قائمة لأن أربعةً تعثّرت.**
//
// **ولماذا هاتان بالذات**: كلتاهما **قائمةٌ مرجعيّةٌ ثابتة** لها جهةٌ
// معلومةٌ وسنةُ إصدارٍ معلومة — **لا ترتيبٌ يتغيّر كلَّ أسبوع** (وهو ما
// يمنع إضافةَ «أفضل ١٠٠ في روتن توميتوز» مثلاً: تتبدّل فتصير بطاقتُنا
// تَعِد ما لا تعطي — D-219).
//
// ⚠️ **والأسماءُ مكتوبةٌ كما تعرفها TMDB لا كما تكتبها الجهة**: «Sunset
// Blvd.» عند AFI و«Sunset Boulevard» عند TMDB، و«M*A*S*H» و«MASH»،
// و«La Règle du jeu» و«The Rules of the Game». **ومن كُتب باسم جهته
// وحدَه لم يكن ليُطابَق أبداً.**
//
// ⚠️ **والسنةُ سنةُ الإصدار في TMDB لا سنةُ القائمة** — للبحث لا للعرض
// (D-144): «كلوز-أب» ١٩٨٩ عند BFI و١٩٩٠ في TMDB.

export interface FamousTitle {
  title: string;
  year: number;
}

/**
 * **AFI's 100 Years…100 Movies — الطبعة العاشرة (٢٠٠٧)**.
 * المصدر: filmsite.org · معهد الفيلم الأمريكي.
 */
export const AFI_100: FamousTitle[] = [
  { title: "Citizen Kane", year: 1941 },
  { title: "The Godfather", year: 1972 },
  { title: "Casablanca", year: 1942 },
  { title: "Raging Bull", year: 1980 },
  { title: "Singin' in the Rain", year: 1952 },
  { title: "Gone with the Wind", year: 1939 },
  { title: "Lawrence of Arabia", year: 1962 },
  { title: "Schindler's List", year: 1993 },
  { title: "Vertigo", year: 1958 },
  { title: "The Wizard of Oz", year: 1939 },
  { title: "City Lights", year: 1931 },
  { title: "The Searchers", year: 1956 },
  { title: "Star Wars", year: 1977 },
  { title: "Psycho", year: 1960 },
  { title: "2001: A Space Odyssey", year: 1968 },
  { title: "Sunset Boulevard", year: 1950 },
  { title: "The Graduate", year: 1967 },
  { title: "The General", year: 1926 },
  { title: "On the Waterfront", year: 1954 },
  { title: "It's a Wonderful Life", year: 1946 },
  { title: "Chinatown", year: 1974 },
  { title: "Some Like It Hot", year: 1959 },
  { title: "The Grapes of Wrath", year: 1940 },
  { title: "E.T. the Extra-Terrestrial", year: 1982 },
  { title: "To Kill a Mockingbird", year: 1962 },
  { title: "Mr. Smith Goes to Washington", year: 1939 },
  { title: "High Noon", year: 1952 },
  { title: "All About Eve", year: 1950 },
  { title: "Double Indemnity", year: 1944 },
  { title: "Apocalypse Now", year: 1979 },
  { title: "The Maltese Falcon", year: 1941 },
  { title: "The Godfather Part II", year: 1974 },
  { title: "One Flew Over the Cuckoo's Nest", year: 1975 },
  { title: "Snow White and the Seven Dwarfs", year: 1937 },
  { title: "Annie Hall", year: 1977 },
  { title: "The Bridge on the River Kwai", year: 1957 },
  { title: "The Best Years of Our Lives", year: 1946 },
  { title: "The Treasure of the Sierra Madre", year: 1948 },
  { title: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", year: 1964 },
  { title: "The Sound of Music", year: 1965 },
  { title: "King Kong", year: 1933 },
  { title: "Bonnie and Clyde", year: 1967 },
  { title: "Midnight Cowboy", year: 1969 },
  { title: "The Philadelphia Story", year: 1940 },
  { title: "Shane", year: 1953 },
  { title: "It Happened One Night", year: 1934 },
  { title: "A Streetcar Named Desire", year: 1951 },
  { title: "Rear Window", year: 1954 },
  { title: "Intolerance", year: 1916 },
  { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
  { title: "West Side Story", year: 1961 },
  { title: "Taxi Driver", year: 1976 },
  { title: "The Deer Hunter", year: 1978 },
  { title: "MASH", year: 1970 },
  { title: "North by Northwest", year: 1959 },
  { title: "Jaws", year: 1975 },
  { title: "Rocky", year: 1976 },
  { title: "The Gold Rush", year: 1925 },
  { title: "Nashville", year: 1975 },
  { title: "Duck Soup", year: 1933 },
  { title: "Sullivan's Travels", year: 1941 },
  { title: "American Graffiti", year: 1973 },
  { title: "Cabaret", year: 1972 },
  { title: "Network", year: 1976 },
  { title: "The African Queen", year: 1951 },
  { title: "Raiders of the Lost Ark", year: 1981 },
  { title: "Who's Afraid of Virginia Woolf?", year: 1966 },
  { title: "Unforgiven", year: 1992 },
  { title: "Tootsie", year: 1982 },
  { title: "A Clockwork Orange", year: 1971 },
  { title: "Saving Private Ryan", year: 1998 },
  { title: "The Shawshank Redemption", year: 1994 },
  { title: "Butch Cassidy and the Sundance Kid", year: 1969 },
  { title: "The Silence of the Lambs", year: 1991 },
  { title: "In the Heat of the Night", year: 1967 },
  { title: "Forrest Gump", year: 1994 },
  { title: "All the President's Men", year: 1976 },
  { title: "Modern Times", year: 1936 },
  { title: "The Wild Bunch", year: 1969 },
  { title: "The Apartment", year: 1960 },
  { title: "Spartacus", year: 1960 },
  { title: "Sunrise: A Song of Two Humans", year: 1927 },
  { title: "Titanic", year: 1997 },
  { title: "Easy Rider", year: 1969 },
  { title: "A Night at the Opera", year: 1935 },
  { title: "Platoon", year: 1986 },
  { title: "12 Angry Men", year: 1957 },
  { title: "Bringing Up Baby", year: 1938 },
  { title: "The Sixth Sense", year: 1999 },
  { title: "Swing Time", year: 1936 },
  { title: "Sophie's Choice", year: 1982 },
  { title: "Goodfellas", year: 1990 },
  { title: "The French Connection", year: 1971 },
  { title: "Pulp Fiction", year: 1994 },
  { title: "The Last Picture Show", year: 1971 },
  { title: "Do the Right Thing", year: 1989 },
  { title: "Blade Runner", year: 1982 },
  { title: "Yankee Doodle Dandy", year: 1942 },
  { title: "Toy Story", year: 1995 },
  { title: "Ben-Hur", year: 1959 },
];

/**
 * **Sight & Sound — أعظم أفلام كلِّ العصور (استفتاء النقّاد ٢٠٢٢)**.
 * المصدر: BFI · معهد الفيلم البريطاني.
 * ⚠️ **المئةُ الأولى وحدَها**: الاستفتاءُ يمتدّ إلى ٢٦٤ فيلماً بالتعادلات،
 * **والمئةُ هي ما يُنشر ويُقرأ**.
 */
export const SIGHT_SOUND_100: FamousTitle[] = [
  { title: "Jeanne Dielman, 23 quai du Commerce, 1080 Bruxelles", year: 1975 },
  { title: "Vertigo", year: 1958 },
  { title: "Citizen Kane", year: 1941 },
  { title: "Tokyo Story", year: 1953 },
  { title: "In the Mood for Love", year: 2000 },
  { title: "2001: A Space Odyssey", year: 1968 },
  { title: "Beau Travail", year: 1999 },
  { title: "Mulholland Drive", year: 2001 },
  { title: "Man with a Movie Camera", year: 1929 },
  { title: "Singin' in the Rain", year: 1952 },
  { title: "Sunrise: A Song of Two Humans", year: 1927 },
  { title: "The Godfather", year: 1972 },
  { title: "The Rules of the Game", year: 1939 },
  { title: "Cleo from 5 to 7", year: 1962 },
  { title: "The Searchers", year: 1956 },
  { title: "Meshes of the Afternoon", year: 1943 },
  { title: "Close-Up", year: 1990 },
  { title: "Persona", year: 1966 },
  { title: "Apocalypse Now", year: 1979 },
  { title: "Seven Samurai", year: 1954 },
  { title: "The Passion of Joan of Arc", year: 1928 },
  { title: "Late Spring", year: 1949 },
  { title: "Playtime", year: 1967 },
  { title: "Do the Right Thing", year: 1989 },
  { title: "The Night of the Hunter", year: 1955 },
  { title: "Au Hasard Balthazar", year: 1966 },
  { title: "Shoah", year: 1985 },
  { title: "Daisies", year: 1966 },
  { title: "Taxi Driver", year: 1976 },
  { title: "Portrait of a Lady on Fire", year: 2019 },
  { title: "Mirror", year: 1975 },
  { title: "Psycho", year: 1960 },
  { title: "8½", year: 1963 },
  { title: "L'Atalante", year: 1934 },
  { title: "Pather Panchali", year: 1955 },
  { title: "City Lights", year: 1931 },
  { title: "M", year: 1931 },
  { title: "Some Like It Hot", year: 1959 },
  { title: "Breathless", year: 1960 },
  { title: "Rear Window", year: 1954 },
  { title: "Bicycle Thieves", year: 1948 },
  { title: "Rashomon", year: 1950 },
  { title: "Killer of Sheep", year: 1978 },
  { title: "Stalker", year: 1979 },
  { title: "The Battle of Algiers", year: 1966 },
  { title: "North by Northwest", year: 1959 },
  { title: "Barry Lyndon", year: 1975 },
  { title: "Wanda", year: 1970 },
  { title: "Ordet", year: 1955 },
  { title: "The 400 Blows", year: 1959 },
  { title: "The Piano", year: 1993 },
  { title: "Ali: Fear Eats the Soul", year: 1974 },
  { title: "News from Home", year: 1977 },
  { title: "Blade Runner", year: 1982 },
  { title: "Battleship Potemkin", year: 1925 },
  { title: "Contempt", year: 1963 },
  { title: "Sherlock Jr.", year: 1924 },
  { title: "The Apartment", year: 1960 },
  { title: "Sans Soleil", year: 1983 },
  { title: "Moonlight", year: 2016 },
  { title: "La Dolce Vita", year: 1960 },
  { title: "Daughters of the Dust", year: 1991 },
  { title: "Casablanca", year: 1942 },
  { title: "Goodfellas", year: 1990 },
  { title: "The Third Man", year: 1949 },
  { title: "Touki Bouki", year: 1973 },
  { title: "The Gleaners and I", year: 2000 },
  { title: "La Jetee", year: 1962 },
  { title: "Andrei Rublev", year: 1966 },
  { title: "Metropolis", year: 1927 },
  { title: "The Red Shoes", year: 1948 },
  { title: "My Neighbor Totoro", year: 1988 },
  { title: "Journey to Italy", year: 1954 },
  { title: "L'Avventura", year: 1960 },
  { title: "Imitation of Life", year: 1959 },
  { title: "Sansho the Bailiff", year: 1954 },
  { title: "Spirited Away", year: 2001 },
  { title: "Satantango", year: 1994 },
  { title: "A Brighter Summer Day", year: 1991 },
  { title: "Celine and Julie Go Boating", year: 1974 },
  { title: "Sunset Boulevard", year: 1950 },
  { title: "Modern Times", year: 1936 },
  { title: "A Matter of Life and Death", year: 1946 },
  { title: "Blue Velvet", year: 1986 },
  { title: "Pierrot le Fou", year: 1965 },
  { title: "The Spirit of the Beehive", year: 1973 },
  { title: "Chungking Express", year: 1994 },
  { title: "The Shining", year: 1980 },
  { title: "The Earrings of Madame de...", year: 1953 },
  { title: "The Leopard", year: 1963 },
  { title: "Ugetsu", year: 1953 },
  { title: "Yi Yi", year: 2000 },
  { title: "Parasite", year: 2019 },
  { title: "Get Out", year: 2017 },
  { title: "Tropical Malady", year: 2004 },
  { title: "Black Girl", year: 1966 },
  { title: "The General", year: 1926 },
  { title: "A Man Escaped", year: 1956 },
  { title: "Once Upon a Time in the West", year: 1968 },
  { title: "Le Mepris", year: 1963 },
];
